import { useDispatch, useSelector } from 'react-redux'

import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import WalletForm from './WalletForm';
import { selectWallets } from '../redux/wallets/selectors';
import Link from 'next/link'

export default function Home() {
  const wallets = useSelector(selectWallets);

  return (
    <div className={styles.container}>
      <Head>
        <title>Wallets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WalletForm />

        {wallets.map(wallet => (
          <Link key={wallet.address} href={`/${wallet.address}`}>{wallet.alias} ({wallet.address})</Link>
        ))}
      </main>
    </div>
  )
}
